In [33]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = "train.csv" # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [21]:
decorrelated_tx, deleted_features = decorrelate_features(tX)
print(decorrelated_tx.shape)
print(deleted_features)

(250000, 20)
[ 5  6 12 26 27 28 21 29 24 25]


In [22]:
usable_tx, usable_indices = delete_outliers(decorrelated_tx, -990)
usable_tx = usable_tx[0]
print(usable_tx.shape)

(68114, 20)


In [35]:
augmented_features = polynomial_embedding(usable_tx)
print(augmented_features.shape)
print(augmented_features[0:5, 0])
print(augmented_features[0:5, 20])

(68114, 60)
[138.47   89.744 148.754 114.744 141.481]
[19173.9409    8053.985536 22127.752516 13166.185536 20016.873361]


In [ ]:
offset_tX = add_offset(usable_tx)
w_init_offset = 1e-2*np.ones((offset_tX.shape[1],))
usable_y = y[usable_indices]


"""
# TOY MODEL :

toy_X = np.random.rand(100, 2)
toy_offset_X = add_offset(toy_X)

toy_y = 2*toy_offset_X[:, 0] + toy_offset_X[:, 1] + 3*toy_offset_X[:, 2]   # y = 2 + X1 + 3*X2

#w_init_offset = 1e-2*np.ones((offset_X.shape[1],))
w_init_toy = np.array([1, 1, 3])"""

"""
test_tX = offset_tX[:, :2]
w_init_test = 1e-2*np.ones((test_tX.shape[1],))

w_init = 1e-2*np.ones((tX.shape[1],))"""

In [ ]:
w_final, losses = SGD(usable_y, offset_tX, w_init_offset, 1e-3, 100, print_stuff=10, batch_size = 100, return_losses=True)
#w_final, losses = SGD(toy_y, toy_offset_X, w_init_toy, 2e-2, 1000, print_stuff=50, batch_size = 100, return_losses=True)
#w, loss = SGD(y, offset_tX, w_init_offset, 100, 1e-2, 128)
#w, loss = least_squares_GD(y, offset_tX, w_init_offset, 100, 1e-3)
#print(w_final)
#plt.plot(np.linspace(0, 1000, 1000), losses, 'b')
#print(losses)

## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)