In [21]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from implementations import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [3]:
from proj1_helpers import *
DATA_TRAIN_PATH = "train.csv" # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [15]:
print(tX[0:10, 28])

[  -2.475 -999.    -999.    -999.    -999.       3.106   -2.767 -999.
 -999.    -999.   ]


In [22]:
data, ids = divide_in_groups(tX)
print(data[0].shape)
print(data[1].shape)
print(data[2].shape)
print(data[3].shape)
print(data[4].shape)
print(data[5].shape)
print(data[0])

(26123, 19)
(7562, 21)
(4429, 29)
(73790, 20)
(69982, 22)
(68114, 30)
[[ 86.24   79.692  27.201 ... 250.178   0.      0.   ]
 [109.412  14.398  17.323 ... 198.616   0.      0.   ]
 [ 85.186  68.827   5.042 ... 151.816   0.      0.   ]
 ...
 [ 71.989  36.548   5.042 ... 144.665   0.      0.   ]
 [ 58.179  68.083  22.439 ...  80.408   0.      0.   ]
 [ 72.756  70.831   7.479 ...  99.405   0.      0.   ]]


## Do your thing crazy machine learning thing here :) ...

In [177]:
PCX, P, ids = PCA(tX, threshold=.9)
print(PCX.shape)
print(ids)
print(P.shape)

(250000, 10)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)
(30, 30)


In [46]:
nonzero_var_tx = delete_zero_var_features(tX)
print(nonzero_var_tx.shape)

(250000, 30)


In [48]:
decorrelated_tx, deleted_features = decorrelate_features(nonzero_var_tx)
print(decorrelated_tx.shape)
print(deleted_features)

(250000, 20)
[ 5  6 12 26 27 28 21 29 24 25]


In [49]:
usable_tx, usable_indices = delete_outliers(decorrelated_tx, -990)
usable_tx = usable_tx[0]
print(usable_tx.shape)

(68114, 20)


In [51]:
augmented_features = polynomial_embedding(usable_tx)
print(augmented_features.shape)

(68114, 40)


In [ ]:
offset_tX = add_offset(usable_tx)
w_init_offset = 1e-2*np.ones((offset_tX.shape[1],))
usable_y = y[usable_indices] 


"""
# TOY MODEL :

toy_X = np.random.rand(100, 2)
toy_offset_X = add_offset(toy_X)

toy_y = 2*toy_offset_X[:, 0] + toy_offset_X[:, 1] + 3*toy_offset_X[:, 2]   # y = 2 + X1 + 3*X2

#w_init_offset = 1e-2*np.ones((offset_X.shape[1],))
w_init_toy = np.array([1, 1, 3])"""

"""
test_tX = offset_tX[:, :2]
w_init_test = 1e-2*np.ones((test_tX.shape[1],))

w_init = 1e-2*np.ones((tX.shape[1],))"""

In [ ]:
w_final, losses = SGD(usable_y, offset_tX, w_init_offset, 1e-3, 100, print_stuff=10, batch_size = 100, return_losses=True)
#w_final, losses = SGD(toy_y, toy_offset_X, w_init_toy, 2e-2, 1000, print_stuff=50, batch_size = 100, return_losses=True)
#w, loss = SGD(y, offset_tX, w_init_offset, 100, 1e-2, 128)
#w, loss = least_squares_GD(y, offset_tX, w_init_offset, 100, 1e-3)
#print(w_final)
#plt.plot(np.linspace(0, 1000, 1000), losses, 'b')
#print(losses)

In [147]:
A = np.array([[1, 2, 3], [2, 5, 6], [3, 8, 9]])
print(A)
print(np.var(A, axis=0))

#B = np.array([1, 2, 3, 4])
#print(B[np.where(B<4)])

[[1 2 3]
 [2 5 6]
 [3 8 9]]
[0.66666667 6.         6.        ]


## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)