In [13]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
x = np.array([[1,2,3,4],[1,3,4,5],[1,4,2,5],[1,6,7,8],[1,5,2,3]])
print(x)

[[1 2 3 4]
 [1 3 4 5]
 [1 4 2 5]
 [1 6 7 8]
 [1 5 2 3]]


In [21]:
from delete_line import *
m = delete(x,2) 
print(m)

[[1 3 4 5]
 [1 6 7 8]]
